/**
 * @fileoverview CRM Tag Mongoose model.
 * Collection: `crm_tags`
 *
 * Tags are lightweight labels applied to contacts for segmentation and flow triggers.
 * System tags (e.g., "VIP", "lost") are auto-generated by lifecycle updaters
 * and cannot be deleted by users.
 *
 * @module domain/models/crm/Tag
 */

import mongoose, { Schema, type Document, type Types } from 'mongoose';

/** TypeScript interface for the CRM Tag document */
export interface ITagDocument extends Document {
  _id: Types.ObjectId;
  restaurantId: Types.ObjectId;
  /** Tag display name */
  name: string;
  /** Optional description */
  description: string | null;
  /** Hex color for UI display (e.g., "#FF5733") */
  color: string | null;
  /** System tags (VIP, lost, recovered) cannot be deleted */
  isSystem: boolean;
  /** Denormalized count of contacts with this tag */
  contactCount: number;
  createdAt: Date;
  updatedAt: Date;
}

const TagSchema = new Schema<ITagDocument>(
  {
    restaurantId: { type: Schema.Types.ObjectId, required: true },
    name: { type: String, required: true },
    description: { type: String, default: null },
    color: { type: String, default: null },
    isSystem: { type: Boolean, default: false },
    contactCount: { type: Number, default: 0, min: 0 },
  },
  {
    collection: 'crm_tags',
    timestamps: true,
  },
);

/** Unique tag name per restaurant */
TagSchema.index({ restaurantId: 1, name: 1 }, { unique: true });

export const Tag = mongoose.model<ITagDocument>('CrmTag', TagSchema);
